require 'spec_helper'

describe package('php5-fpm') do
  it { should be_installed }
end

describe package('php5-cli') do
  it { should be_installed }
end

describe package('php5-common') do
  it { should be_installed }
end

describe package('php5-gd') do
  it { should be_installed }
end

describe service('php5-fpm') do
  it { should be_enabled }
  it { should be_running }
end

describe file('/etc/php5/fpm/php-fpm.conf') do
  it { should be_file }
  it { should contain 'Generated by Chef' }
end

describe file('/etc/php5/fpm/pool.d/www.conf') do
  it { should be_file }
  it { should contain 'Chef generated configuration' }
end

describe port(9000) do
  it { should be_listening.on('127.0.0.1').with('tcp') }
end
